pipeline {
   agent any
   environment {
       POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
       VENV_DIR = 'venv'
       REPORT_DIR = 'html_report'
       REPORT_FILE = 'report.html'
   }
   stages {
       stage('Checkout') {
           steps {
               checkout scm
           }
       }
       stage('Set up Python') {
           steps {
               sh '''
                   python3 -m venv $VENV_DIR
                   . $VENV_DIR/bin/activate
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
               '''
           }
       }
       stage('Run tests') {
           steps {
               sh '''
                   . $VENV_DIR/bin/activate
                   mkdir -p $REPORT_DIR
                   pytest tests -m "parquet_data" \
                     --db_host="postgres" \
                     --db_port="5432" \
                     --db_name="mydatabase" \
                     --db_user="$POSTGRES_SECRET_USR" \
                     --db_password="$POSTGRES_SECRET_PSW" \
                     --html=$REPORT_DIR/$REPORT_FILE \
                     --self-contained-html
               '''
           }
       }
       stage('Archive test report') {
           steps {
               archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
               publishHTML(target: [
                   allowMissing: false,
                   keepAll: true,
                   reportDir: 'html_report',
                   reportFiles: 'report.html',
                   reportName: 'HTML Test Report'
               ])
           }
       }
   }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}
